### ISSUE TITLE
Error while in combat - <unnamed>:SetSize()) during combat lockdown.

### ISSUE THREAD

**Issue by Aubergin** [mooreatv/DynamicBoxer#80]
Date: 2021-04-05 00:14:50
ID: 1
Error occured in: AddOn: DynamicBoxer
Count: 32
Message: Note: AddOn DynamicBoxer attempted to call a protected function (<unnamed>:SetSize()) during combat lockdown.
Debug:
   [C]: SetSize()
   DynamicBoxer\MoLib/MoLibUI.lua:163: calcCorners()
   DynamicBoxer\MoLib/MoLibUI.lua:174: setSizeToChildren()
   DynamicBoxer\MoLib/MoLibUI.lua:101: Snap()
   DynamicBoxer\MoLib/MoLibUI.lua:1373:
      DynamicBoxer\MoLib/MoLibUI.lua:1370
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.4.4
  AtlasLootClassic, vv1.5.9
  AtlasLootClassicData, vv1.5.9
  AtlasLootClassicDungeonsAndRaids, vv1.5.9
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Bagnon, v9.0.6
  Bartender4, v4.10.7
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Binder, v2.8.0
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, vv1.3.21
  ClassicCastbarsOptions, vv1.3.21
  Details, v
  DynamicBoxer, vv3.03.02
  EMAClassic, vv1.13.5-Release-v0.9(121033)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.7.3
  GogoLoot, v1.6
  GSE, v2.6.51
  GSEGUI, v2.6.51
  GSELDB, v2.6.51
  HealCommClassic, v
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.99
  LeatrixPlus, v1.13.99
  Mama, vv1.1.5
  ModernTargetFrame, v1.8
  OmniCC, v8.1.1
  Prat30, v3.9.1
  Prat30Libraries, v
  StarCursor, vr6-classic
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v10.1.5
  TinyTooltip, v9.0.1
  TitanClassic, v1.2.8.11306
  TitanClassicAmmo, v1.2.8.11306
  TitanClassicBag, v1.2.8.11306
  TitanClassicClock, v1.2.8.11306
  TitanClassicGold, v1.2.8.11306
  TitanClassicLocation, v1.2.8.11306
  TitanClassicLootType, v1.2.8.11306
  TitanClassicPerformance, v1.2.8.11306
  TitanClassicRegen, v1.2.8.11306
  TitanClassicRepair, v1.2.8.11306
  TitanClassicVolume, v1.2.8.11306
  TitanClassicXP, v1.2.8.11306
  VendorPrice, v1.3.8
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=787)

**Comment by mooreatv** [comment]
fixed in 3.6!
