### ISSUE TITLE
Suggestion: print help commands as multiple items instead of a single one

### ISSUE THREAD

**Issue by Muricas** [mooreatv/DynamicBoxer#81]
When I type `/dbox help`, the text that is printed to the chat frame only shows the buttom of the text due to the height of my chat windows being less than the number of rows in the print command:

![image](https://user-images.githubusercontent.com/81184564/115132567-13893700-9fc7-11eb-8bac-7ebec9388e41.png)

If I scroll up, I cannot view the cut off text as the default chat window seems to scroll per entry, not per line. This is the result of a single mousewheel scroll tick:

![chat](https://user-images.githubusercontent.com/81184564/115132604-46cbc600-9fc7-11eb-9ff0-fb457d790d2e.gif)

I've observed in other addons similar features where each command is printed to the chat window individually, such that you can still scroll and see all the commands. `/tsm help`:

![tsm](https://user-images.githubusercontent.com/81184564/115132630-84305380-9fc7-11eb-8780-ec3d8fe8f022.gif)

**Comment by mooreatv** [comment]
excellent suggestion and that was bugging me; fixed in MoLib for all my addons (when I repush them) fixed in dbox 3.04.01!
